make warnings more verbose
carlculator/timeseriesx pull request #47
Opened 2022-07-14 14:59 UTC by carlculator

2022-07-18 05:47 UTC, TimoGuenther requested changes

2022-07-18 05:47 UTC, TimoGuenther commented on timeseriesx/mixins/time_zone.py
> +class TimeZoneWarning(Warning):
`TimeZoneWarning` and `UnitWarning` could be a subclasses of `RuntimeWarning`.

2022-07-18 05:47 UTC, TimoGuenther commented on timeseriesx/mixins/time_zone.py
> +    pass
A short docstring explaining the intended use and purpose of `TimeZoneWarning` and `UnitWarning` would be helpful.

2022-07-18 05:47 UTC, TimoGuenther commented on timeseriesx/base/timestamp_series.py
> +                          category=RuntimeWarning)
For improved traceability, the category could be a custom warning class like `TimeZoneWarning` and `UnitWarning`.

2022-07-18 10:35 UTC, carlculator commented on timeseriesx/base/timestamp_series.py
> +                          category=RuntimeWarning)
I don't have a good name for it. Any sugesstions?

2022-07-18 10:42 UTC, TimoGuenther commented on timeseriesx/base/timestamp_series.py
> +                          category=RuntimeWarning)
Perhaps `TimestampMismatchWarning` or `MismatchedTimestampsWarning`.

2022-07-18 11:39 UTC, carlculator commented on timeseriesx/mixins/time_zone.py
> +class TimeZoneWarning(Warning):
ok. done.

2022-07-18 11:39 UTC, carlculator commented on timeseriesx/mixins/time_zone.py
> +    pass
ok. done.

2022-07-18 11:40 UTC, carlculator commented on timeseriesx/base/timestamp_series.py
> +                          category=RuntimeWarning)
thanks. applied it

2022-07-18 14:50 UTC, merged

2022-07-19 05:12 UTC, TimoGuenther commented
This merge was premature considering the changes were not endorsed yet. Indeed, I would propose further changes: The `pass` below the docstrings are redundant because `pass` is only syntactical.